name = "re"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "43.218.77.16:443"
UUID = "9257df75-0961-4fb8-a9fe-94cbff0baca3"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
